// AUTO-GENERATED — DO NOT EDIT.
// 再生成: `node scripts/generate-shiki-aliases.ts` または `npm run build`。
// Shiki version: 4.1.0
//
// Shiki bundledLanguagesInfo の全言語 (フル同梱) を正規名へ canonicalize し、エイリアスを
// 併せて吐き出した結果。CLI (--shiki-langs=<csv>) と browser 側 Shiki 初期化、scanFencedLangs
// が同じマップを参照する。

export const SHIKI_SUPPORTED_LANGS = [
  'abap',
  'actionscript-3',
  'ada',
  'angular-html',
  'angular-ts',
  'apache',
  'apex',
  'apl',
  'applescript',
  'ara',
  'asciidoc',
  'asm',
  'astro',
  'awk',
  'ballerina',
  'bat',
  'beancount',
  'berry',
  'bibtex',
  'bicep',
  'bird2',
  'blade',
  'bsl',
  'c',
  'c3',
  'cadence',
  'cairo',
  'clarity',
  'clojure',
  'cmake',
  'cobol',
  'codeowners',
  'codeql',
  'coffee',
  'common-lisp',
  'coq',
  'cpp',
  'crystal',
  'csharp',
  'css',
  'csv',
  'cue',
  'cypher',
  'd',
  'dart',
  'dax',
  'desktop',
  'diff',
  'docker',
  'dotenv',
  'dream-maker',
  'edge',
  'elixir',
  'elm',
  'emacs-lisp',
  'erb',
  'erlang',
  'fennel',
  'fish',
  'fluent',
  'fortran-fixed-form',
  'fortran-free-form',
  'fsharp',
  'gdresource',
  'gdscript',
  'gdshader',
  'genie',
  'gherkin',
  'git-commit',
  'git-rebase',
  'gleam',
  'glimmer-js',
  'glimmer-ts',
  'glsl',
  'gn',
  'gnuplot',
  'go',
  'graphql',
  'groovy',
  'hack',
  'haml',
  'handlebars',
  'haskell',
  'haxe',
  'hcl',
  'hjson',
  'hlsl',
  'html',
  'html-derivative',
  'http',
  'hurl',
  'hxml',
  'hy',
  'imba',
  'ini',
  'java',
  'javascript',
  'jinja',
  'jison',
  'json',
  'json5',
  'jsonc',
  'jsonl',
  'jsonnet',
  'jssm',
  'jsx',
  'julia',
  'just',
  'kdl',
  'kotlin',
  'kusto',
  'latex',
  'lean',
  'less',
  'liquid',
  'llvm',
  'log',
  'logo',
  'lua',
  'luau',
  'make',
  'markdown',
  'marko',
  'matlab',
  'mdc',
  'mdx',
  'mermaid',
  'mipsasm',
  'mojo',
  'moonbit',
  'move',
  'narrat',
  'nextflow',
  'nextflow-groovy',
  'nginx',
  'nim',
  'nix',
  'nushell',
  'objective-c',
  'objective-cpp',
  'ocaml',
  'odin',
  'openscad',
  'pascal',
  'perl',
  'php',
  'pkl',
  'plsql',
  'po',
  'polar',
  'postcss',
  'powerquery',
  'powershell',
  'prisma',
  'prolog',
  'proto',
  'pug',
  'puppet',
  'purescript',
  'python',
  'qml',
  'qmldir',
  'qss',
  'r',
  'racket',
  'raku',
  'razor',
  'reg',
  'regexp',
  'rel',
  'riscv',
  'ron',
  'rosmsg',
  'rst',
  'ruby',
  'rust',
  'sas',
  'sass',
  'scala',
  'scheme',
  'scss',
  'sdbl',
  'shaderlab',
  'shellscript',
  'shellsession',
  'smalltalk',
  'solidity',
  'soy',
  'sparql',
  'splunk',
  'sql',
  'ssh-config',
  'stata',
  'stylus',
  'surrealql',
  'svelte',
  'swift',
  'system-verilog',
  'systemd',
  'talonscript',
  'tasl',
  'tcl',
  'templ',
  'terraform',
  'tex',
  'toml',
  'ts-tags',
  'tsv',
  'tsx',
  'turtle',
  'twig',
  'typescript',
  'typespec',
  'typst',
  'v',
  'vala',
  'vb',
  'verilog',
  'vhdl',
  'viml',
  'vue',
  'vue-html',
  'vue-vine',
  'vyper',
  'wasm',
  'wenyan',
  'wgsl',
  'wikitext',
  'wit',
  'wolfram',
  'xml',
  'xsl',
  'yaml',
  'zenscript',
  'zig',
] as const

export type SupportedLang = (typeof SHIKI_SUPPORTED_LANGS)[number]

export const ALIAS_TO_CANONICAL: Readonly<Record<string, SupportedLang>> = {
  '1c': 'bsl',
  '1c-query': 'sdbl',
  abap: 'abap',
  'actionscript-3': 'actionscript-3',
  ada: 'ada',
  adoc: 'asciidoc',
  'angular-html': 'angular-html',
  'angular-ts': 'angular-ts',
  apache: 'apache',
  apex: 'apex',
  apl: 'apl',
  applescript: 'applescript',
  ara: 'ara',
  asciidoc: 'asciidoc',
  asm: 'asm',
  astro: 'astro',
  awk: 'awk',
  ballerina: 'ballerina',
  bash: 'shellscript',
  bat: 'bat',
  batch: 'bat',
  be: 'berry',
  beancount: 'beancount',
  berry: 'berry',
  bibtex: 'bibtex',
  bicep: 'bicep',
  bird: 'bird2',
  bird2: 'bird2',
  blade: 'blade',
  bsl: 'bsl',
  c: 'c',
  'c#': 'csharp',
  'c++': 'cpp',
  c3: 'c3',
  cadence: 'cadence',
  cairo: 'cairo',
  cdc: 'cadence',
  cjs: 'javascript',
  clarity: 'clarity',
  clj: 'clojure',
  clojure: 'clojure',
  'closure-templates': 'soy',
  cmake: 'cmake',
  cmd: 'vb',
  cobol: 'cobol',
  codeowners: 'codeowners',
  codeql: 'codeql',
  coffee: 'coffee',
  coffeescript: 'coffee',
  'common-lisp': 'common-lisp',
  console: 'shellsession',
  coq: 'coq',
  cpp: 'cpp',
  cql: 'cypher',
  crystal: 'crystal',
  cs: 'csharp',
  csharp: 'csharp',
  css: 'css',
  csv: 'csv',
  cts: 'typescript',
  cue: 'cue',
  cypher: 'cypher',
  d: 'd',
  dart: 'dart',
  dax: 'dax',
  desktop: 'desktop',
  diff: 'diff',
  docker: 'docker',
  dockerfile: 'docker',
  dotenv: 'dotenv',
  'dream-maker': 'dream-maker',
  edge: 'edge',
  elisp: 'emacs-lisp',
  elixir: 'elixir',
  elm: 'elm',
  'emacs-lisp': 'emacs-lisp',
  erb: 'erb',
  erl: 'erlang',
  erlang: 'erlang',
  f: 'fortran-fixed-form',
  'f#': 'fsharp',
  f03: 'fortran-free-form',
  f08: 'fortran-free-form',
  f18: 'fortran-free-form',
  f77: 'fortran-fixed-form',
  f90: 'fortran-free-form',
  f95: 'fortran-free-form',
  fennel: 'fennel',
  fish: 'fish',
  fluent: 'fluent',
  for: 'fortran-fixed-form',
  'fortran-fixed-form': 'fortran-fixed-form',
  'fortran-free-form': 'fortran-free-form',
  fs: 'fsharp',
  fsharp: 'fsharp',
  fsl: 'jssm',
  ftl: 'fluent',
  gd: 'gdscript',
  gdresource: 'gdresource',
  gdscript: 'gdscript',
  gdshader: 'gdshader',
  genie: 'genie',
  gherkin: 'gherkin',
  'git-commit': 'git-commit',
  'git-rebase': 'git-rebase',
  gjs: 'glimmer-js',
  gleam: 'gleam',
  'glimmer-js': 'glimmer-js',
  'glimmer-ts': 'glimmer-ts',
  glsl: 'glsl',
  gn: 'gn',
  gnuplot: 'gnuplot',
  go: 'go',
  gql: 'graphql',
  graphql: 'graphql',
  groovy: 'groovy',
  gts: 'glimmer-ts',
  hack: 'hack',
  haml: 'haml',
  handlebars: 'handlebars',
  haskell: 'haskell',
  haxe: 'haxe',
  hbs: 'handlebars',
  hcl: 'hcl',
  hjson: 'hjson',
  hlsl: 'hlsl',
  hs: 'haskell',
  html: 'html',
  'html-derivative': 'html-derivative',
  http: 'http',
  hurl: 'hurl',
  hxml: 'hxml',
  hy: 'hy',
  imba: 'imba',
  ini: 'ini',
  jade: 'pug',
  java: 'java',
  javascript: 'javascript',
  jinja: 'jinja',
  jison: 'jison',
  jl: 'julia',
  js: 'javascript',
  json: 'json',
  json5: 'json5',
  jsonc: 'jsonc',
  jsonl: 'jsonl',
  jsonnet: 'jsonnet',
  jssm: 'jssm',
  jsx: 'jsx',
  julia: 'julia',
  just: 'just',
  kdl: 'kdl',
  kotlin: 'kotlin',
  kql: 'kusto',
  kt: 'kotlin',
  kts: 'kotlin',
  kusto: 'kusto',
  latex: 'latex',
  lean: 'lean',
  lean4: 'lean',
  less: 'less',
  liquid: 'liquid',
  lisp: 'common-lisp',
  lit: 'ts-tags',
  llvm: 'llvm',
  log: 'log',
  logo: 'logo',
  lua: 'lua',
  luau: 'luau',
  make: 'make',
  makefile: 'make',
  markdown: 'markdown',
  marko: 'marko',
  matlab: 'matlab',
  mbt: 'moonbit',
  mbti: 'moonbit',
  md: 'markdown',
  mdc: 'mdc',
  mdx: 'mdx',
  mediawiki: 'wikitext',
  mermaid: 'mermaid',
  mips: 'mipsasm',
  mipsasm: 'mipsasm',
  mjs: 'javascript',
  mmd: 'mermaid',
  mojo: 'mojo',
  moonbit: 'moonbit',
  move: 'move',
  mts: 'typescript',
  nar: 'narrat',
  narrat: 'narrat',
  nextflow: 'nextflow',
  'nextflow-groovy': 'nextflow-groovy',
  nf: 'nextflow',
  nginx: 'nginx',
  nim: 'nim',
  nix: 'nix',
  nu: 'nushell',
  nushell: 'nushell',
  objc: 'objective-c',
  'objective-c': 'objective-c',
  'objective-cpp': 'objective-cpp',
  ocaml: 'ocaml',
  odin: 'odin',
  openscad: 'openscad',
  pascal: 'pascal',
  perl: 'perl',
  perl6: 'raku',
  php: 'php',
  pkl: 'pkl',
  plsql: 'plsql',
  po: 'po',
  polar: 'polar',
  postcss: 'postcss',
  pot: 'po',
  potx: 'po',
  powerquery: 'powerquery',
  powershell: 'powershell',
  prisma: 'prisma',
  prolog: 'prolog',
  properties: 'ini',
  proto: 'proto',
  protobuf: 'proto',
  ps: 'powershell',
  ps1: 'powershell',
  pug: 'pug',
  puppet: 'puppet',
  purescript: 'purescript',
  py: 'python',
  python: 'python',
  ql: 'codeql',
  qml: 'qml',
  qmldir: 'qmldir',
  qss: 'qss',
  r: 'r',
  racket: 'racket',
  raku: 'raku',
  razor: 'razor',
  rb: 'ruby',
  reg: 'reg',
  regex: 'regexp',
  regexp: 'regexp',
  rel: 'rel',
  riscv: 'riscv',
  ron: 'ron',
  rosmsg: 'rosmsg',
  rs: 'rust',
  rst: 'rst',
  ruby: 'ruby',
  rust: 'rust',
  sas: 'sas',
  sass: 'sass',
  scad: 'openscad',
  scala: 'scala',
  scheme: 'scheme',
  scss: 'scss',
  sdbl: 'sdbl',
  sh: 'shellscript',
  shader: 'shaderlab',
  shaderlab: 'shaderlab',
  shell: 'shellscript',
  shellscript: 'shellscript',
  shellsession: 'shellsession',
  smalltalk: 'smalltalk',
  solidity: 'solidity',
  soy: 'soy',
  sparql: 'sparql',
  spl: 'splunk',
  splunk: 'splunk',
  sql: 'sql',
  'ssh-config': 'ssh-config',
  stata: 'stata',
  styl: 'stylus',
  stylus: 'stylus',
  surql: 'surrealql',
  surrealql: 'surrealql',
  svelte: 'svelte',
  swift: 'swift',
  'system-verilog': 'system-verilog',
  systemd: 'systemd',
  talon: 'talonscript',
  talonscript: 'talonscript',
  tasl: 'tasl',
  tcl: 'tcl',
  templ: 'templ',
  terraform: 'terraform',
  tex: 'tex',
  tf: 'terraform',
  tfvars: 'terraform',
  toml: 'toml',
  tres: 'gdresource',
  ts: 'typescript',
  'ts-tags': 'ts-tags',
  tscn: 'gdresource',
  tsp: 'typespec',
  tsv: 'tsv',
  tsx: 'tsx',
  turtle: 'turtle',
  twig: 'twig',
  typ: 'typst',
  typescript: 'typescript',
  typespec: 'typespec',
  typst: 'typst',
  v: 'v',
  vala: 'vala',
  vb: 'vb',
  verilog: 'verilog',
  vhdl: 'vhdl',
  vim: 'viml',
  viml: 'viml',
  vimscript: 'viml',
  vue: 'vue',
  'vue-html': 'vue-html',
  'vue-vine': 'vue-vine',
  vy: 'vyper',
  vyper: 'vyper',
  wasm: 'wasm',
  wenyan: 'wenyan',
  wgsl: 'wgsl',
  wiki: 'wikitext',
  wikitext: 'wikitext',
  wit: 'wit',
  wl: 'wolfram',
  wolfram: 'wolfram',
  xml: 'xml',
  xsl: 'xsl',
  yaml: 'yaml',
  yml: 'yaml',
  zenscript: 'zenscript',
  zig: 'zig',
  zsh: 'shellscript',
  文言: 'wenyan',
}
