// Step 3b: KaTeX CSS のフォント data URI 化 + minimal/extra への分離。
// `katex/dist/katex.min.css` を読み、`@font-face { ... url(fonts/*.woff2) ... }` ブロックを
// `url(data:font/woff2;base64,...)` に書き換え、`url(*.ttf)` / `url(*.woff)` は
// `local("")` (空 local() = CSS Level 3 仕様で常に miss、 次の src へフォールスルー) に
// 潰す。woff2 fallthrough は modern target 全サポート前提
// (docs/mdxg-math-rendering.archive.md §3.1 / §5.g)。
// 旧設計では `url(about:blank)` を使っていたが、 CSP `font-src data:` の制約で
// `about:` scheme が許可されておらず、 ブラウザが src を順に試す挙動で 1 つ目の
// `about:blank` が CSP violation として Console に noise を出していた (実描画は
// 2 つ目の woff2 data URI で成功するため実害なし)。 `local("")` は CSP の評価対象に
// ならず、 noise を構造的に消す標準 idiom。
//
// 2 系統に分岐して書き出す:
//   - dist/katex/katex.css         : minimal セット (Main / AMS / Math / Size1〜4 の 9 family)
//                                     + 全 `.katex` CSS ルール (font-face 以外を全部)
//   - dist/katex/katex-fonts-extra.css : extra セット (Caligraphic / Fraktur / Script /
//                                       SansSerif / Typewriter の 11 family) の `@font-face` のみ
// CLI の `--math-fonts all` 指定時 / standalone build は両方を inline する
// (Step 3c / Step 4)。
//
// KaTeX major version up 時にこの分類が破れていないか先頭の version assert が検知する。
// scripts/lib/shiki-meta.ts と同じ「version pin + dist 構造 assert」パターン
// (docs/mdxg-math-rendering.archive.md §5.j)。

import { dirname, resolve } from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const KATEX_DIST = resolve(ROOT_DIR, 'node_modules', 'katex', 'dist')
const FONTS_DIR = resolve(KATEX_DIST, 'fonts')
const OUT_DIR = resolve(ROOT_DIR, 'dist', 'katex')

// 挙動を実証した上で pin している KaTeX バージョン。major / minor / patch まで pin し、
// 版が動いた瞬間に build を fail させて下記チェックリストの再評価を強制する。
// 番号だけ上げて通す対応は禁止 (このアサート自体がそれを防ぐための番人)。
//
// === KaTeX バージョン更新時 再評価チェックリスト (これだけで完結する) ===
//   1. trust:false セキュリティ境界: \href / \url / \includegraphics / \htmlClass /
//      \htmlStyle / \htmlData を renderToString({ trust: false, strict: 'warn' }) に通し、
//      <a href> / <img> / 任意 HTML / class 注入が出ず escape された best-effort 描画に
//      なること。LLM 生成数式を信頼しない前提の XSS 防御線 (DESIGN.md §11)。
//   2. フォントセット: katex.min.css の @font-face root が既知 12 種のみで新規/改名/削除が
//      ないこと (minimal = Main/Math/AMS/Size1-4、extra = Caligraphic/Fraktur/Script/
//      SansSerif/Typewriter)。全 @font-face block に woff2 url があること
//      (.ttf/.woff を local("") に潰し woff2 へ fallthrough する本スクリプトの前提)。
//   3. renderToString API 契約: 同期で文字列を返し、文法エラー -> katex-error class /
//      未知マクロ -> best-effort <mtext> (katex-error なし) の判定境界が維持されること
//      (ブラウザ側 data-math-failed 判定がこの境界に依存)。
//   4. </script> sanity: katex.mjs に literal </script> が含まれないこと (注入時の
//      エンコード規約、core/embed.ts)。
// 1 / 2 / 3 は src/app/renderers/katex.ts の "KaTeX version contract" in-source test で
// 継続検証している (pin 更新時はそのテストを通せば 1-3 の実証になる)。4 は
// src/core/embed/script-encoding.ts の escapeScriptTagInJs が無条件 escape で担保する。
// 設計判断の背景は docs/mdxg-math-rendering.archive.md §5.f / §5.g / §5.j / Step 5b。
const EXPECTED_KATEX_VERSION = '0.17.0'

// minimal セットに含めるフォント family 名 (KaTeX_ prefix 後の root 名)。
// 数式の支配的記法 (\frac / \sum / \int / ギリシャ文字 / 行列 / 角括弧 / \mathbb) を網羅する。
const MINIMAL_FAMILY_ROOTS = new Set(['AMS', 'Main', 'Math', 'Size1', 'Size2', 'Size3', 'Size4'])

const HEADER_COMMENT_MINIMAL = `/* Generated by scripts/build-katex-css.ts from katex@${EXPECTED_KATEX_VERSION}.
 * minimal family set (Main / AMS / Math / Size1-4): docs/mdxg-math-rendering.archive.md §5.g / §5.l
 * Do not edit by hand — re-run \`npm run build:katex\` to regenerate. */
`

const HEADER_COMMENT_EXTRA = `/* Generated by scripts/build-katex-css.ts from katex@${EXPECTED_KATEX_VERSION}.
 * extra family set (Caligraphic / Fraktur / Script / SansSerif / Typewriter):
 * see docs/mdxg-math-rendering.archive.md §5.g / §5.l. CLI \`--math-fonts all\` / standalone build only.
 * Do not edit by hand — re-run \`npm run build:katex\` to regenerate. */
`

interface Stats {
  dropped: number
  extra: number
  inlined: number
  minimal: number
}

type BlockKind = 'fontface' | 'other'

interface Block {
  content: string
  kind: BlockKind
}

interface Classification {
  content: string
  target: 'extra' | 'minimal'
}

const assertKatexVersion = async (): Promise<void> => {
  const pkgPath = resolve(KATEX_DIST, '..', 'package.json')
  const raw = await readFile(pkgPath, 'utf8')
  const parsed: unknown = JSON.parse(raw)
  if (typeof parsed !== 'object' || parsed === null || !('version' in parsed)) {
    throw new Error('katex/package.json から version を読み取れませんでした')
  }
  const { version } = parsed
  if (version !== EXPECTED_KATEX_VERSION) {
    throw new Error(
      `katex version mismatch: expected ${EXPECTED_KATEX_VERSION}, got ${String(version)}. ` +
        '本ファイル冒頭の「再評価チェックリスト」(1.trust:false セキュリティ / 2.フォントセット / ' +
        '3.renderToString 契約 / 4.</script> sanity) を実証してから EXPECTED_KATEX_VERSION を更新すること。'
    )
  }
}

// `@font-face{font-display:block;font-family:"KaTeX_SansSerif";...}` 形式から root 名を取り出す。
// 引用符 (`"KaTeX_SansSerif"`) と裸 (`KaTeX_Main`) の両方を許容する。
const extractFontFamilyRoot = (block: string): string | null => {
  const match = /font-family:"?KaTeX_([A-Za-z0-9]+)"?/.exec(block)
  if (match === null) {
    return null
  }
  const [, root] = match
  return root
}

// `url(fonts/X.woff2)` の 1 件を data URI に置換する非同期ステップ。
// woff2 以外は `local("")` に潰す (空 local family は CSS Level 3 仕様で常に miss、
// 次の src へフォールスルー、 CSP `font-src data:` の評価対象にならず Console noise を出さない)。
const buildUrlReplacement = async (
  match: RegExpMatchArray
): Promise<{ from: string; kind: 'dropped' | 'inlined'; to: string }> => {
  const [original, file] = match
  if (file.endsWith('.woff2')) {
    const buf = await readFile(resolve(FONTS_DIR, file))
    return {
      from: original,
      kind: 'inlined',
      to: `url(data:font/woff2;base64,${buf.toString('base64')})`,
    }
  }
  return { from: original, kind: 'dropped', to: 'local("")' }
}

const inlineWoff2InBlock = async (block: string, stats: Stats): Promise<string> => {
  const matches = [...block.matchAll(/url\(fonts\/([^)]+)\)/g)]
  const replacements = await Promise.all(matches.map(buildUrlReplacement))
  let result = block
  for (const { from, kind, to } of replacements) {
    result = result.replace(from, to)
    if (kind === 'inlined') {
      stats.inlined += 1
    } else {
      stats.dropped += 1
    }
  }
  return result
}

const splitFontFaces = (css: string): Block[] => {
  const blocks: Block[] = []
  let lastEnd = 0
  for (const match of css.matchAll(/@font-face\{[^}]*\}/g)) {
    if (match.index > lastEnd) {
      blocks.push({ content: css.slice(lastEnd, match.index), kind: 'other' })
    }
    blocks.push({ content: match[0], kind: 'fontface' })
    lastEnd = match.index + match[0].length
  }
  if (lastEnd < css.length) {
    blocks.push({ content: css.slice(lastEnd), kind: 'other' })
  }
  return blocks
}

// font-face ブロックを minimal/extra のどちらに割り振るか + woff2 inline 後の content。
const classifyFontFaceBlock = async (block: Block, stats: Stats): Promise<Classification> => {
  const root = extractFontFamilyRoot(block.content)
  const rewritten = await inlineWoff2InBlock(block.content, stats)
  const isMinimal = root !== null && MINIMAL_FAMILY_ROOTS.has(root)
  if (isMinimal) {
    stats.minimal += 1
    return { content: rewritten, target: 'minimal' }
  }
  stats.extra += 1
  return { content: rewritten, target: 'extra' }
}

const collectFontFaceClassifications = async (
  blocks: Block[],
  stats: Stats
): Promise<Classification[]> =>
  Promise.all(
    blocks
      .filter((block) => block.kind === 'fontface')
      .map(async (block) => classifyFontFaceBlock(block, stats))
  )

interface DistributeCtx {
  buckets: { extra: string[]; minimal: string[] }
  classifications: Classification[]
  cursor: { value: number }
}

const appendBlock = (block: Block, ctx: DistributeCtx): void => {
  if (block.kind === 'other') {
    ctx.buckets.minimal.push(block.content)
    return
  }
  const classification = ctx.classifications[ctx.cursor.value]
  ctx.cursor.value += 1
  ctx.buckets[classification.target].push(classification.content)
}

const distributeBlocks = async (
  blocks: Block[],
  stats: Stats
): Promise<{ extraCss: string; minimalCss: string }> => {
  const classifications = await collectFontFaceClassifications(blocks, stats)
  const ctx: DistributeCtx = {
    buckets: { extra: [HEADER_COMMENT_EXTRA], minimal: [HEADER_COMMENT_MINIMAL] },
    classifications,
    cursor: { value: 0 },
  }
  for (const block of blocks) {
    appendBlock(block, ctx)
  }
  return { extraCss: ctx.buckets.extra.join(''), minimalCss: ctx.buckets.minimal.join('') }
}

const reportStats = (stats: Stats, minimalCss: string, extraCss: string): void => {
  console.log(
    `[build-katex-css] minimal=${stats.minimal} families, extra=${stats.extra} families, ` +
      `${stats.inlined} woff2 inlined, ${stats.dropped} ttf/woff dropped`
  )
  console.log(
    `[build-katex-css] dist/katex/katex.css ${minimalCss.length} bytes, ` +
      `dist/katex/katex-fonts-extra.css ${extraCss.length} bytes`
  )
}

const build = async (): Promise<void> => {
  await assertKatexVersion()
  const css = await readFile(resolve(KATEX_DIST, 'katex.min.css'), 'utf8')
  const blocks = splitFontFaces(css)
  const stats: Stats = { dropped: 0, extra: 0, inlined: 0, minimal: 0 }
  const { extraCss, minimalCss } = await distributeBlocks(blocks, stats)
  await mkdir(OUT_DIR, { recursive: true })
  await Promise.all([
    writeFile(resolve(OUT_DIR, 'katex.css'), minimalCss),
    writeFile(resolve(OUT_DIR, 'katex-fonts-extra.css'), extraCss),
  ])
  reportStats(stats, minimalCss, extraCss)
}

await build()
